config/routes.rb
Rails.application.routes.draw do
  resources :teams, only: [ :index, :show, :new, :create ] do
    resources :questions, only: [ :new, :create ]
  end

  resources :play, only: [ :index ] do
    collection do
      get 'start'
      get 'quiz'
      get 'answers'
      get 'rankings'
      get 'winner'

      post 'next'
      post 'buzz'
    end
  end

  resources :events, only: [ :index, :show, :new, :create ]

  root 'teams#new'
end

app/controllers/play_controller.rb
class PlayController < ApplicationController
  before_action :set_event, only: [ :start, :next, :quiz, :rankings, :buzz, :answers, :winner ]
  before_action :set_team, only: [ :quiz, :buzz, :answers ]
  before_action :set_question, only: [ :start, :next, :answers ]
  before_action :set_standings, only: [ :start, :quiz, :rankings, :winner ]
  skip_before_action :check_if_done

  def index
  end

  def start
    question = { id: @question.id, content: @question.content, points: @question.points, asked: @asked }
    PrivatePub.publish_to "/questions/active", question
  end

  def next
    if @event
      @question.asked = true
      @question.save
      delete_question_session

      corrects = params[:correct] || {}
      @event.teams.each do |team|
        correct = corrects[team.id.to_s]
        points = correct ? @question.points : 0

        score = @question.scores.find_by_team_id(team.id)
        if score
          score.points = points
          score.save
        end
      end
    end

    redirect_to :start_play_index
  end

  def quiz
    unless @event.all_questions_asked?
      @question = Question.new({ content: '', points: 0, asked: 0 })
      @number = 0
    else
      redirect_to :winner_play_index
    end
  end

  def buzz
    score = Score.new event_id: @event.id, team_id: @team.id, answer: params[:answer]

    @question = Question.find params[:question_id]
    @question.scores << score
  end

  def answers
    @teams = @event.teams
    @answers = @question.scores
  end

  def rankings
  end

  def winner
  end

  private

  def set_event
    if session[:event_id]
      @event = Event.find session[:event_id]
    else
      @event = Event.last
      session[:event_id] = @event.id
    end

    @event
  end

  def set_team
    if session[:team_id]
      @team = @event.teams.find session[:team_id]
    else
      redirect_to new_team_path, alert: 'Only registered teams are allowed to join. Kindly register.'
    end
  end

  def set_question
    question_id = session[:question_id] || params[:question_id]
    if question_id
      @question = @event.questions.find question_id
    else
      unless @event.all_questions_asked?
        @question = @event.questions.unasked.shuffle.first
        session[:question_id] = @question.id
      else
        PrivatePub.publish_to "/questions/done", none: ''
        redirect_to :winner_play_index
      end
    end
    @asked = @event.questions.asked.size + 1
  end

  def set_standings
    standings = {}
    @rankings = {}

    @event.teams.each do |t|
      standings[t.id] = 0
    end

    @event.questions.asked.each do |q|
      q.scores.each do |s|
        standings[s.team_id] += s.points.nil? ? 0 : s.points
      end
    end

    standings = standings.sort_by { |id, value| value }.reverse
    standings.each do |id, points|
      team = @event.teams.find id
      @rankings[team.name] = points
    end

    @rankings
  end

  def delete_question_session
    session.delete(:question_id)
  end
end

app/views/play/_leader_board.html.slim
section.leader-board
  .panel.panel-primary
    .panel-heading
      h2.text-center Leaderboard
    .panel-body
      table.table
        thead
          tr
            th Team
            th.text-right Score
        tbody
          - rankings.each do |team, points|
            tr
              td = team
              td.text-right = points

app/views/play/_question.html.slim
.question-area
  input type="hidden" name="question_id" id="question_id" value="#{question.id}"
  h1
    | Question ##{asked}
    small &nbsp;#{question.points}pt#{question.points > 1 ? 's' :''}

  .question.page-header
    => question.content

  .timer
    span.countdown-row.countdown-show
      span.countdown-section
        span.countdown-amount 30
        span.countdown-period Seconds

  .answer-field.hide
    a.btn.btn-lg.btn-primary href="#" Show Answer

  h1.answer.hide.text-success
    = question.answer

.points.hide
  = form_tag({action: :next}, method: :post) do |f|
    input type="hidden" name="question_id" value="#{question.id}"

    h3 Team Answers
    ul.list-unstyled

    button.btn.btn-lg.btn-primary type="submit" Next Question

app/views/play/_rankings.html.slim
- rankings.each do |team, points|
  tr
    td = team
    td.text-right = points

app/views/play/_team_answers.html.slim
- teams.each do |t|
  li
    .row
      .col-md-1
        .nice-cb
          input type="checkbox" name="correct[#{t.id}]" value="none" id="team-#{t.id}"
          label for="team-#{t.id}"
      .col-md-5
        = t.name
      .col-md-6
        - team = answers.find_by_team_id(t.id)
        - if team
            strong = team.answer
        - else
            i No answer given

app/views/play/answers.js.erb
$('#quiz-server ul').append("<%= j(render 'team_answers', teams: @teams, answers: @answers)%>")

app/views/play/index.html.slim
.nerd-lightning
.row
  .start
    = link_to "Game time. Let's get in on!", start_play_index_path, class: 'btn btn-lg btn-primary'

app/views/play/quiz.html.slim
.text-center = @team.name

#waiting
  .nerd-lightning
  h1.text-center Waiting for the next question...

#quiz-client.hidden
  .row.quiz-page
    section.quiz-main
      .question-area
        h1
          | Question #
          span 1
          small 1pt

        .question.page-header

        .timer
          span.countdown-row.countdown-show
            span.countdown-section
              span.countdown-amount 30
              span.countdown-period Seconds

    = render 'leader_board', rankings: @rankings

  .row
    .col-md-9
      .form-group
        label What is your answer?
        = text_field_tag 'answer', nil, class: "form-control input-lg", placeholder: "Hmmm... tama kaya?", autofocus: "true"
        input type="hidden" name="question_id" id="question_id" value=""

app/views/play/rankings.js.erb
$('.leader-board tbody').html('').append("<%= j(render 'rankings', rankings: @rankings)%>")

app/views/play/start.html.slim
#quiz-server
  .row.quiz-page
    section.quiz-main
      - if @question
        = render 'question', question: @question, asked: @asked
      - else
        .nerd-lightning
        h1.text-center Waiting for the next question...

    = render 'leader_board', rankings: @rankings

app/views/play/winner.html.slim
.nerd-lightning
br
.jumbotron
  h1.text-center Congratulations
  h1.text-center.winner = @rankings.first[0]
  h1.text-center Nerd Fight Champions

h1 Official Results

.standings
  - @rankings.each do |team, points|
    .row
      .col-md-6
        = team
      .col-md-2
        = points